'use client'

import { useMemo, useRef, useState } from 'react'
import { Area, AreaChart, CartesianGrid, Line, LineChart, ReferenceArea, Tooltip, XAxis, YAxis } from 'recharts'
import { AlertCircle, ArrowRight, Beaker, Check, CircleHelp, Download, FileText, FlaskConical, Leaf, Play, RotateCcw, ScanLine, Upload, Waves } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { ChartContainer, ChartTooltipContent } from '@/components/ui/chart'
import { Crop, downloadText, makeSyntheticSpectrum, processingSteps, reportText, riceExamples, riceWorkflow, simulatePrediction, sorghumExamples, sorghumWorkflow, SpectrumPoint, toCsv, validateCsv, wavelengthBands } from '@/lib/grain-demo'

const navItems = [['demo','Interactive demo'],['visual','Visualization'],['workflow','How it works'],['research','Research'],['roadmap','Roadmap']]
function Kicker({ children }: { children: React.ReactNode }) { return <p className="mb-3 text-xs font-bold uppercase tracking-[0.18em] text-primary">{children}</p> }
function DemoBadge() { return <span className="inline-flex items-center gap-2 rounded-full border border-primary/25 bg-primary/10 px-3 py-1.5 text-xs font-semibold text-primary"><span className="size-1.5 rounded-full bg-primary" />Demo mode — simulated results</span> }
function InfoTip({ children }: { children: React.ReactNode }) { return <span className="group relative inline-flex align-middle"><CircleHelp className="ml-1 size-3.5 text-muted-foreground" /><span className="pointer-events-none absolute bottom-full left-1/2 z-10 mb-2 hidden w-56 -translate-x-1/2 rounded-lg bg-foreground px-3 py-2 text-xs font-normal leading-5 text-background shadow-lg group-hover:block">{children}</span></span> }

export default function GrainDemo() {
  const [crop, setCrop] = useState<Crop>('Rice')
  const [exampleId, setExampleId] = useState(riceExamples[0].id)
  const [points, setPoints] = useState<SpectrumPoint[]>(() => makeSyntheticSpectrum('Rice', riceExamples[0].id))
  const [sampleName, setSampleName] = useState(riceExamples[0].name)
  const [error, setError] = useState(''); const [running, setRunning] = useState(false); const [step, setStep] = useState(-1)
  const [result, setResult] = useState<ReturnType<typeof simulatePrediction> | null>(null); const fileRef = useRef<HTMLInputElement>(null)
  const examples = crop === 'Rice' ? riceExamples : sorghumExamples
  const chartConfig = { reflectance: { label: 'Reflectance', color: 'var(--chart-1)' }, protein: { label: 'Protein signal', color: 'var(--chart-2)' }, moisture: { label: 'Moisture signal', color: 'var(--chart-3)' } }
  const derived = useMemo(() => points.map((point, index) => ({ ...point, protein: Math.min(1, point.reflectance + 0.035 * Math.sin(index / 8)), moisture: Math.min(1, 0.92 - point.reflectance + 0.025 * Math.cos(index / 11)) })), [points])
  const selectedBands = useMemo(() => wavelengthBands.filter((band) => points.some((point) => point.wavelength_nm >= Number(band.range.split('–')[0]) && point.wavelength_nm <= Number(band.range.split('–')[1]))), [points])

  function selectCrop(nextCrop: Crop) { const next = nextCrop === 'Rice' ? riceExamples[0] : sorghumExamples[0]; setCrop(nextCrop); setExampleId(next.id); setPoints(makeSyntheticSpectrum(nextCrop, next.id)); setSampleName(next.name); setResult(null); setError(''); setStep(-1) }
  function loadExample() { const example = examples.find((item) => item.id === exampleId) ?? examples[0]; setPoints(makeSyntheticSpectrum(crop, example.id)); setSampleName(example.name); setResult(null); setError(''); setStep(-1) }
  function handleFile(file?: File) { if (!file) return; const reader = new FileReader(); reader.onload = () => { const parsed = validateCsv(String(reader.result)); if (parsed.error) { setError(parsed.error); return }; setPoints(parsed.points ?? []); setSampleName(file.name.replace(/\.csv$/i, '')); setResult(null); setError(''); setStep(-1) }; reader.readAsText(file) }
  function runAnalysis() { setRunning(true); setResult(null); setStep(0); let current = 0; const timer = window.setInterval(() => { current += 1; setStep(current); if (current >= processingSteps.length) { window.clearInterval(timer); setResult(simulatePrediction(points, crop)); setRunning(false) } }, 600) }
  function reset() { selectCrop('Rice') }
  const flow = crop === 'Rice' ? riceWorkflow : sorghumWorkflow

  return <main className="min-h-screen bg-background text-foreground"><header className="sticky top-0 z-20 border-b border-border/70 bg-background/90 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between gap-5 px-5 py-4 lg:px-8"><a href="#top" className="flex items-center gap-3"><span className="flex size-9 items-center justify-center rounded-xl bg-primary text-primary-foreground"><Waves className="size-5" /></span><span className="font-semibold tracking-tight">GrainScope <span className="text-muted-foreground">/ spectral lab</span></span></a><nav className="hidden items-center gap-5 text-sm text-muted-foreground md:flex">{navItems.map(([id, label]) => <a key={id} href={`#${id}`} className="transition-colors hover:text-primary">{label}</a>)}</nav><DemoBadge /></div></header>
    <section id="top" className="border-b border-border/70"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-14 lg:grid-cols-[1.05fr_.95fr] lg:px-8 lg:py-20"><div className="flex flex-col justify-center"><Kicker>Group 2 project · hyperspectral imaging</Kicker><h1 className="max-w-3xl text-balance text-4xl font-semibold tracking-[-0.04em] sm:text-6xl">See how invisible wavelengths become grain quality.</h1><p className="mt-6 max-w-xl text-pretty text-lg leading-8 text-muted-foreground">A step-by-step teaching prototype for estimating protein and moisture from calibrated grain reflectance — with every processing stage visible.</p><div className="mt-8 flex flex-wrap gap-3"><Button size="lg" onClick={() => document.getElementById('demo')?.scrollIntoView({ behavior: 'smooth' })}><Play data-icon="inline-start" />Open interactive demo</Button><a href="#workflow" className="inline-flex h-10 items-center rounded-md border border-border px-4 text-sm font-medium hover:bg-muted">Read the method</a></div></div><div className="rounded-3xl border border-primary/20 bg-primary/5 p-6"><div className="flex items-center justify-between"><span className="text-sm font-semibold">Wavelength bands</span><span className="font-mono text-xs text-muted-foreground">{points[0]?.wavelength_nm}–{points.at(-1)?.wavelength_nm} nm</span></div><div className="mt-7 space-y-3">{selectedBands.map((band) => <div key={band.label} className="flex items-center gap-3 rounded-xl border border-border/70 bg-background/70 p-3"><span className="size-3 rounded-full" style={{ background: band.color }} /><div className="flex-1"><div className="text-sm font-semibold">{band.label}</div><div className="font-mono text-xs text-muted-foreground">{band.range}</div></div><ArrowRight className="size-4 text-muted-foreground" /></div>)}</div><p className="mt-5 text-xs leading-5 text-muted-foreground">Each band carries a different clue. Models combine them rather than relying on a single colour.</p></div></div></section>

    <section id="demo" className="mx-auto max-w-7xl scroll-mt-20 px-5 py-16 lg:px-8"><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><Kicker>01 · interactive demo</Kicker><h2 className="text-3xl font-semibold tracking-tight">Process a grain spectrum, one stage at a time</h2><p className="mt-2 max-w-3xl text-muted-foreground">Start with a built-in sample or upload a CSV with <code className="rounded bg-muted px-1.5 py-0.5 text-xs">wavelength_nm,reflectance</code>. The outputs below are deterministic illustrations, not laboratory results.</p></div><DemoBadge /></div><div className="grid gap-6 lg:grid-cols-[.7fr_1.3fr]"><aside className="rounded-2xl border border-border bg-card p-5 shadow-sm"><div className="flex items-center gap-2 text-sm font-semibold"><Beaker className="size-4 text-primary" />Sample setup</div><div className="mt-5 flex gap-2 rounded-lg bg-muted p-1"><button className={`flex-1 rounded-md px-3 py-2 text-sm font-medium ${crop === 'Rice' ? 'bg-background text-primary shadow-sm' : 'text-muted-foreground'}`} onClick={() => selectCrop('Rice')}>Rice</button><button className={`flex-1 rounded-md px-3 py-2 text-sm font-medium ${crop === 'Sorghum' ? 'bg-background text-primary shadow-sm' : 'text-muted-foreground'}`} onClick={() => selectCrop('Sorghum')}>Sorghum</button></div><label className="mt-6 block text-xs font-semibold uppercase tracking-wider text-muted-foreground">Built-in sample</label><select value={exampleId} onChange={(e) => setExampleId(e.target.value)} className="mt-2 h-10 w-full rounded-md border border-input bg-background px-3 text-sm"><optgroup label={crop}>{examples.map((example) => <option key={example.id} value={example.id}>{example.name}</option>)}</optgroup></select><div className="mt-3 flex gap-2"><Button variant="secondary" className="flex-1" onClick={loadExample}><FlaskConical data-icon="inline-start" />Load example</Button><Button variant="outline" size="icon" onClick={reset} aria-label="Reset demo"><RotateCcw /></Button></div><div className="my-6 border-t border-border" /><input ref={fileRef} type="file" accept=".csv,text/csv" className="sr-only" onChange={(e) => handleFile(e.target.files?.[0])} /><Button variant="outline" className="w-full" onClick={() => fileRef.current?.click()}><Upload data-icon="inline-start" />Upload CSV</Button>{error && <div className="mt-3 flex gap-2 rounded-lg border border-destructive/30 bg-destructive/10 p-3 text-xs leading-5 text-destructive"><AlertCircle className="size-4 shrink-0" />{error}</div>}<Button className="mt-6 w-full" size="lg" onClick={runAnalysis} disabled={running || !points.length}>{running ? 'Processing…' : 'Run full analysis'}</Button><p className="mt-3 text-center text-xs text-muted-foreground">{points.length} spectral measurements loaded</p></aside>

      <div className="min-w-0 space-y-6"><div className="rounded-2xl border border-border bg-card p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="flex items-center gap-2 text-sm font-semibold"><ScanLine className="size-4 text-primary" />{sampleName}<InfoTip>Reflectance is the fraction of incident light returned by the sample.</InfoTip></div><p className="mt-1 text-xs text-muted-foreground">Raw calibrated signal · x-axis uses nanometres</p></div><div className="flex flex-wrap gap-2">{selectedBands.map((band) => <span key={band.label} className="inline-flex items-center gap-1.5 rounded-full border border-border px-2.5 py-1 text-[11px] font-medium"><span className="size-2 rounded-full" style={{ background: band.color }} />{band.label}</span>)}</div></div><div className="mt-5 h-[280px] w-full"><ChartContainer config={chartConfig} className="h-full w-full"><AreaChart data={points}><defs><linearGradient id="reflectanceFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="var(--color-reflectance)" stopOpacity={0.38} /><stop offset="100%" stopColor="var(--color-reflectance)" stopOpacity={0.02} /></linearGradient></defs><CartesianGrid vertical={false} strokeDasharray="3 3" /><XAxis dataKey="wavelength_nm" tickLine={false} axisLine={false} tickMargin={8} minTickGap={30} /><YAxis domain={[0, 1]} tickLine={false} axisLine={false} width={34} /><Tooltip content={<ChartTooltipContent />} /><Area type="monotone" dataKey="reflectance" stroke="var(--color-reflectance)" fill="url(#reflectanceFill)" strokeWidth={2} dot={false} /><ReferenceArea x1={700} x2={900} fill="var(--color-protein)" fillOpacity={0.04} /></AreaChart></ChartContainer></div></div>

      <div className="rounded-2xl border border-border bg-card p-5 shadow-sm"><div className="flex items-center justify-between"><div><div className="text-sm font-semibold">Processing pipeline</div><p className="mt-1 text-xs text-muted-foreground">Watch the input become model-ready features.</p></div><span className="font-mono text-xs text-muted-foreground">{step < 0 ? 'idle' : `${Math.min(step + 1, processingSteps.length)}/${processingSteps.length}`}</span></div><div className="mt-5 grid gap-3 sm:grid-cols-5">{processingSteps.map((item, index) => <div key={item} className={`rounded-xl border p-3 transition ${step === index ? 'border-primary bg-primary/10' : step > index ? 'border-chart-2/40 bg-chart-2/10' : 'border-border bg-muted/30'}`}><div className="flex items-center gap-2">{step > index ? <Check className="size-4 text-chart-2" /> : <span className="font-mono text-xs text-muted-foreground">0{index + 1}</span>}<span className="text-xs font-semibold">{item}</span></div><p className="mt-2 text-[11px] leading-4 text-muted-foreground">{['Check CSV shape and ranges','Remove scatter and baseline effects','Highlight useful wavelength bands','Estimate composition targets','Summarise simulated predictions'][index]}</p></div>)}</div></div>

      <div className="grid gap-6 xl:grid-cols-2"><ChartCard title="Protein signal" subtitle="Broad absorption features used for the protein estimate" data={derived} dataKey="protein" color="var(--color-protein)" config={chartConfig} /><ChartCard title="Moisture signal" subtitle="Water-sensitive response across the spectrum" data={derived} dataKey="moisture" color="var(--color-moisture)" config={chartConfig} /></div>
      {result && <div className="rounded-2xl border border-primary/30 bg-primary/10 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><Kicker>Simulated result</Kicker><h3 className="text-xl font-semibold">Quality estimate for {sampleName}</h3></div><div className="flex gap-2"><Button variant="outline" size="sm" onClick={() => downloadText(`${sampleName}-report.txt`, reportText(crop, sampleName, result))}><FileText data-icon="inline-start" />Report</Button><Button variant="outline" size="sm" onClick={() => downloadText(`${sampleName}-spectrum.csv`, toCsv(points), 'text/csv')}><Download data-icon="inline-start" />CSV</Button></div></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><Metric label="Protein" value={`${result.protein} g/100 g`} tone="protein" /><Metric label="Moisture" value={`${result.moisture} g/100 g`} tone="moisture" /><Metric label="Mean reflectance" value={String(result.mean)} tone="reflectance" /></div><p className="mt-4 text-xs leading-5 text-muted-foreground">Simulated from synthetic reflectance. Do not use this prototype for food safety, grading, purchasing, or scientific conclusions.</p></div>}</div></div></section>

    <section id="visual" className="scroll-mt-20 border-y border-border/70 bg-muted/30"><div className="mx-auto max-w-7xl px-5 py-16 lg:px-8"><Kicker>02 · illustrative visualization</Kicker><div className="grid gap-8 lg:grid-cols-[.55fr_1.45fr] lg:items-center"><div><h2 className="text-3xl font-semibold tracking-tight">One spectrum, multiple quality stories.</h2><p className="mt-3 leading-7 text-muted-foreground">The same wavelength axis can be transformed into different feature views. Protein and moisture do not appear as literal colours in the grain; they are inferred from patterns learned from labelled samples.</p><div className="mt-6 flex flex-wrap gap-2">{wavelengthBands.map((band) => <span key={band.label} className="rounded-full border border-border bg-background px-3 py-1.5 text-xs font-medium"><span className="mr-1.5 inline-block size-2 rounded-full" style={{ background: band.color }} />{band.label} · {band.range}</span>)}</div></div><div className="grid gap-4 md:grid-cols-2"><VisualCard title="Protein map" description="Illustrative spatial output" colors={['var(--chart-2)','var(--chart-1)','var(--chart-3)']} /><VisualCard title="Moisture map" description="Illustrative water-sensitive output" colors={['var(--chart-3)','var(--chart-4)','var(--chart-1)']} /></div></div></div></section>

    <section id="workflow" className="scroll-mt-20"><div className="mx-auto max-w-7xl px-5 py-16 lg:px-8"><Kicker>03 · how it works</Kicker><h2 className="text-3xl font-semibold tracking-tight">Two crop pathways, one careful data story.</h2><p className="mt-3 max-w-3xl leading-7 text-muted-foreground">The notes distinguish a manageable rice baseline from a deeper sorghum sequence model. Both require paired spectra and laboratory labels from the same physical samples.</p><div className="mt-8 grid gap-6 lg:grid-cols-2">{[{name:'Rice baseline', icon:Leaf, items:riceWorkflow, note:'MSC corrects scatter, SPA selects useful wavelengths, and MLR creates a transparent baseline.'},{name:'Sorghum CLNet', icon:FlaskConical, items:sorghumWorkflow, note:'A 1D CNN learns nearby spectral patterns while an LSTM learns relationships along the ordered spectrum.'}].map(({ name, icon: Icon, items, note }) => <div key={name} className="rounded-2xl border border-border bg-card p-6 shadow-sm"><div className="flex items-center gap-3"><span className="flex size-10 items-center justify-center rounded-xl bg-primary/10 text-primary"><Icon className="size-5" /></span><h3 className="font-semibold">{name}</h3></div><div className="mt-7 flex flex-wrap items-center gap-2">{items.map((item, index) => <div key={item} className="flex items-center gap-2"><span className="rounded-lg border border-primary/20 bg-primary/5 px-3 py-2 text-xs font-medium">{item}</span>{index < items.length - 1 && <ArrowRight className="size-3 text-primary" />}</div>)}</div><p className="mt-6 text-sm leading-6 text-muted-foreground">{note}</p></div>)}</div></div></section>

    <section id="research" className="scroll-mt-20 border-y border-border/70 bg-muted/30"><div className="mx-auto max-w-7xl px-5 py-16 lg:px-8"><Kicker>04 · research background</Kicker><h2 className="text-3xl font-semibold tracking-tight">Content grounded in the project notes.</h2><div className="mt-8 grid gap-5 md:grid-cols-2">{[{crop:'Rice', title:'MSC–SPA–MLR', text:'The supplied notes describe a rice study using Kjeldahl protein labels, 400–1000 nm spectra, and a transparent preprocessing and regression pipeline.', meta:'144 samples · 4 cultivars · 2 harvest years'},{crop:'Sorghum', title:'CNN + LSTM = CLNet', text:'The supplied notes describe a sorghum study measuring protein with Kjeldahl testing and moisture by drying, using about 900–1700 nm spectra.', meta:'240 samples · 12 varieties · protein + moisture'}].map((paper) => <article key={paper.crop} className="rounded-2xl border border-border bg-card p-6"><span className="text-xs font-bold uppercase tracking-wider text-primary">{paper.crop}</span><h3 className="mt-3 text-xl font-semibold">{paper.title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{paper.text}</p><p className="mt-5 font-mono text-xs text-muted-foreground">{paper.meta}</p></article>)}</div></div></section>
    <section id="roadmap" className="scroll-mt-20"><div className="mx-auto max-w-7xl px-5 py-16 lg:px-8"><Kicker>05 · project roadmap</Kicker><h2 className="text-3xl font-semibold tracking-tight">From illustrative demo to validated model.</h2><div className="mt-8 grid gap-3 md:grid-cols-2 lg:grid-cols-4">{['Secure compatible labelled data','Inspect and preprocess spectra','Split by physical sample','Train baseline and deep model','Evaluate R², RMSE and RPD','Connect validated model API'].map((item, index) => <div key={item} className="rounded-xl border border-border bg-card p-4"><span className="font-mono text-xs text-primary">0{index + 1}</span><p className="mt-3 text-sm font-medium leading-5">{item}</p></div>)}</div></div></section>
    <footer className="border-t border-border/70"><div className="mx-auto flex max-w-7xl flex-col gap-3 px-5 py-8 text-sm text-muted-foreground sm:flex-row sm:items-center sm:justify-between lg:px-8"><span>GrainScope · Group 2 project</span><span>Prototype only · synthetic data · no external credentials</span></div></footer>
  </main>
}

function ChartCard({ title, subtitle, data, dataKey, color, config }: { title: string; subtitle: string; data: Array<Record<string, number>>; dataKey: string; color: string; config: Record<string, { label: string; color: string }> }) { return <div className="rounded-2xl border border-border bg-card p-5 shadow-sm"><h3 className="text-sm font-semibold">{title}</h3><p className="mt-1 text-xs text-muted-foreground">{subtitle}</p><div className="mt-4 h-44"><ChartContainer config={config} className="h-full w-full"><LineChart data={data}><CartesianGrid vertical={false} strokeDasharray="3 3" /><XAxis dataKey="wavelength_nm" tickLine={false} axisLine={false} tickMargin={8} minTickGap={35} /><YAxis domain={[0, 1]} tickLine={false} axisLine={false} width={30} /><Tooltip content={<ChartTooltipContent />} /><Line type="monotone" dataKey={dataKey} stroke={color} strokeWidth={2.5} dot={false} /></LineChart></ChartContainer></div></div> }
function Metric({ label, value, tone }: { label: string; value: string; tone: string }) { return <div className="rounded-xl border border-border bg-background/70 p-4"><p className="text-xs font-medium text-muted-foreground">{label}</p><p className="mt-2 text-xl font-semibold" style={{ color: `var(--color-${tone})` }}>{value}</p></div> }
function VisualCard({ title, description, colors }: { title: string; description: string; colors: string[] }) { const cells = Array.from({ length: 64 }, (_, index) => `${colors[index % colors.length]}`); return <div className="rounded-2xl border border-border bg-card p-4"><div className="grid grid-cols-8 gap-1">{cells.map((color, index) => <div key={index} className="aspect-square rounded-sm" style={{ background: color, opacity: 0.35 + ((index * 17) % 55) / 100 }} />)}</div><h3 className="mt-4 text-sm font-semibold">{title}</h3><p className="mt-1 text-xs text-muted-foreground">{description} · not a real image</p></div> }
